apiVersion: apps/v1
kind: Deployment
metadata:
   name: cars
spec:
   selector:
      matchLabels:
         app: cars
   replicas: 1
   template:
     metadata:
       labels:
         app: cars
     spec:
       containers:
         - name: cars
           image: domiruthcr.azurecr.io/cars:latest
           ports:
             - containerPort: 80
             - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
     name: cars
     labels:
      app: cars
spec:
   ports:
     - name: http
       protocol: TCP
       port: 80
       targetPort: 80
     - name: https
       protocol: TCP
       port: 443
       targetPort: 443
   selector:
     app: cars
   type: LoadBalancer
