apiVersion: apps/v1
kind: Deployment
metadata:
   name: policy
spec:
   selector:
      matchLabels:
         app: policy
   replicas: 2
   template:
     metadata:
       labels:
         app: policy
     spec:
       containers:
         - name: policy
           image: domiruthcr.azurecr.io/policy:latest
           ports:
             - containerPort: 80
             - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
     name: policy
     labels:
      app: policy
spec:
   ports:
     - name: http
       protocol: TCP
       port: 80
       targetPort: 80
     - name: https
       protocol: TCP
       port: 443
       targetPort: 443
   selector:
     app: policy
   type: LoadBalancer
